# Um compose para iniciar o RabbitMQ e posteriormente os serviços de microserviços
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq  
  
  payments-service:
    build: 
      context: ./services/payments.service
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "5000:8080"
    container_name: online.store.payments-service
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq-network
    volumes:
      - .:/app/payments/publish
      - ~/.aspnet/https:/https:ro

  orders-service:
    build: 
      context: ./services/orders.service
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "5001:8080"
    container_name: online.store.orders-service
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq-network
    volumes:
      - .:/app/orders/publish
      - ~/.aspnet/https:/https:ro
    
  
  warehouse-service:
    build: 
      context: ./services/warehouse.service
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "5002:8080"
    container_name: online.store.warehouse-service
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq-network
    volumes:
      - .:/app/warehouse/publish
      - ~/.aspnet/https:/https:ro

  delivery-service:
    build: 
      context: ./services/delivery.service
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "5003:8080"
    container_name: online.store.delivery-service
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq-network
    volumes:
      - .:/app/delivery/publish
      - ~/.aspnet/https:/https:ro

networks:
  rabbitmq-network:
    driver: bridge

volumes:
  rabbitmq-data:
    driver: local